-- 004: a candidate profile's id IS the user's account id
-- (Partly superseded by 005: ids are generated by this service again.)
--
-- Applied to Supabase on 2026-09-27.
-- One profile per user, so a separate generated id added nothing. The id now
-- comes from the user account (auth service) and is the same `candidateId`
-- every RoleFit service uses. Child tables keep referencing candidate_profile(id).
--
-- Note: the UPDATE below only works while the child tables are empty (their
-- foreign keys have no ON UPDATE CASCADE). That was the case when applied,
-- and is always the case on a fresh database.

BEGIN;

UPDATE candidate_profile SET id = user_id;

ALTER TABLE candidate_profile ALTER COLUMN id DROP DEFAULT;
ALTER TABLE candidate_profile DROP COLUMN user_id;

COMMENT ON COLUMN candidate_profile.id IS
  'The user''s account id (from the auth service). One profile per user.';

COMMIT;
