-- 005: this service generates candidate ids again
--
-- Applied to Supabase on 2026-09-27.
-- The Candidate Profile Service owns the candidate's identity: a new profile
-- gets a generated id, and other RoleFit services link to that id
-- (their `candidateId`). There is still no separate user_id column (see 004).

ALTER TABLE candidate_profile ALTER COLUMN id SET DEFAULT gen_random_uuid();

COMMENT ON COLUMN candidate_profile.id IS
  'Candidate id, generated by this service. Other services reference it as candidateId.';
