/**
 * Domain types for candidate profiles.
 *
 * These are shared by REST controllers, gRPC handlers, the service layer and
 * the repository. Keep them independent of Express, gRPC and SQL.
 *
 * The shape follows the frontend contract (rolefit-frontend/src/lib/types.ts),
 * so the REST API can return a CandidateProfile as-is. The repository maps it
 * to and from the tables in db/migrations (camelCase here, snake_case in SQL).
 */

export type EmploymentType = 'Full-time' | 'Part-time' | 'Internship' | 'Contract';
export type WorkArrangement = 'On-site' | 'Hybrid' | 'Remote';

/** One row of `work_experience`. */
export interface Experience {
  id: string;
  /** job_title */
  role: string;
  /** company_name */
  organization: string;
  /** start_date, 'YYYY-MM-DD' */
  start: string;
  /** end_date, 'YYYY-MM-DD'. Missing = current job (is_current = true). */
  end?: string;
  bullets: string[];
}

/** One row of `project`. */
export interface Project {
  id: string;
  name: string;
  tech: string[];
  bullets: string[];
}

/** One row of `education`. */
export interface Education {
  id: string;
  degree: string;
  /** institution_name */
  school: string;
  /** Free text: '2026' or '2022 - 2026'. */
  year: string;
}

/** The `job_preference` row (at most one per candidate). */
export interface CandidatePreferences {
  /** preferred_locations */
  locations: string[];
  /** work_arrangements */
  arrangements: WorkArrangement[];
  employmentTypes: EmploymentType[];
  /** minimum_salary */
  minSalary?: number;
}

/**
 * Everything the candidate (or the AI, from a resume) can fill in.
 * Used for confirming an extracted profile and, as a Partial, for updates.
 */
export interface ProfileData {
  name: string;
  headline: string;
  email: string;
  location: string;
  links: string[];
  summary: string;
  /** One `candidate_skill` row per name. */
  skills: string[];
  experience: Experience[];
  projects: Project[];
  education: Education[];
  preferences: CandidatePreferences;
}

/** A stored profile, as returned by GET /api/profiles/:candidateId. */
export interface CandidateProfile extends ProfileData {
  /**
   * candidate_profile.id, generated by this service when the profile is
   * created. This is the `candidateId` used in the API and by other services.
   */
  id: string;
  /** Calculated from `name` (e.g. 'Pimchanok Srisuk' -> 'PS'), not stored. */
  initials: string;
  /** true once the candidate confirmed data extracted from a resume. */
  verified: boolean;
  /** 0-100, calculated from how many sections are filled in, not stored. */
  completeness: number;
  createdAt: Date;
  updatedAt: Date;
}

/**
 * Input for createProfile(): what the candidate enters when registering.
 * Everything else starts empty and is filled in later (edit or resume import).
 */
export interface CreateProfileInput {
  name: string;
  email: string;
}

/** Input for importResume(): the uploaded resume file. */
export interface ImportResumeInput {
  fileName: string;
  /** e.g. 'application/pdf' */
  mimeType: string;
  content: Buffer;
}

/**
 * Result of importResume(). NOT saved: the candidate reviews it first and
 * then sends `profile` back to confirmExtractedProfile().
 */
export interface ExtractedProfile {
  fileName: string;
  profile: ProfileData;
}

/** Input for confirmExtractedProfile(). */
export interface ConfirmProfileInput {
  /** The existing profile to overwrite (created earlier by createProfile). */
  candidateId: string;
  /** The extracted data after the candidate reviewed and corrected it. */
  profile: ProfileData;
}

/**
 * Input for updateProfile(). Every field is optional: only the fields sent
 * are changed. A list (skills, experience, ...) is replaced as a whole.
 */
export type UpdateProfileInput = Partial<ProfileData>;
