import type { Pool,PoolClient } from 'pg';
import { NotImplementedError } from '../utils/errors';
import { isUuid } from '../utils/validation';
import type {
  CandidatePreferences,
  CandidateProfile,
  CreateProfileInput,
  Education,
  EmploymentType,
  Experience,
  ProfileData,
  Project,
  UpdateProfileInput,
  WorkArrangement
} from '../types/profile.types';

interface ProfileRow{
  id: string;
  name: string;
  headline: string | null;
  summary: string | null;
  location: string | null;
  email: string | null;
  links: string[];
  verified: boolean;
  created_at: Date;
  updated_at: Date;
}
interface SkillRow{
  id: string;
  candidate_id: string;
  skill_name: string;
  proficiency_level: string | null;
}

interface ProjectRow{
  id: string;
  candidate_id: string;
  name: string;
  tech: string[];
  bullets: string[];
}

interface ExperienceRow{
  id: string;
  candidate_id: string;
  company_name: string;
  job_title: string;
  start_date: string | null;
  end_date: string | null;
  is_current: boolean;
  bullets: string[];
}

interface PreferenceRow{
  id: string;
  candidate_id: string;
  employment_types: string[];
  preferred_roles: string[] | null;
  work_arrangements: string[] | null;
  preferred_locations: string[] | null;
  /** numeric: pg returns it as a string, e.g. '60000' */
  minimum_salary: string | null;
  salary_currency: string | null;
}

interface EducationRow{
  id: string;
  candidate_id: string;
  institution_name: string;
  degree: string;
  field_of_study: string | null;
  year: string | null;
}
/**
 * Data access for candidate profiles.
 *
 * This is the ONLY place in the whole RoleFit system that talks to the
 * candidate profile database. The service layer depends on the interface,
 * which also lets you swap in an in-memory fake for tests.
 *
 * A CandidateProfile is spread over 6 tables: candidate_profile plus
 * candidate_skill, work_experience, project, education and job_preference
 * (see db/migrations). The repository puts it together and takes it apart.
 */
export interface ProfileRepository {
  /**
   * `candidateId` = candidate_profile.id (generated by this service).
   * Returns null when not found.
   */
  findById(candidateId: string): Promise<CandidateProfile | null>;
  /** Creates a new, mostly empty profile. The database generates its id. */
  create(input: CreateProfileInput): Promise<CandidateProfile>;
  /**
   * Overwrites an existing profile with confirmed resume data (verified = true).
   * Returns null when the candidateId doesn't exist.
   */
  saveConfirmed(candidateId: string, data: ProfileData): Promise<CandidateProfile | null>;
  /** Changes only the given fields. Returns null when not found. */
  update(candidateId: string, changes: UpdateProfileInput): Promise<CandidateProfile | null>;
  /** Removes one skill (case-insensitive). Returns false when the candidate doesn't have it. */
  deleteSkill(candidateId: string, skillName: string): Promise<boolean>;
}

export class PostgresProfileRepository implements ProfileRepository {
  constructor(private readonly pool: Pool) {}

  async findById(candidateId: string): Promise<CandidateProfile | null> {
    // TODO 5: Load the candidate_profile row and its child rows, and map
    // them to a CandidateProfile (including the calculated initials and
    // completeness). Return null when no row exists.
    const profileResult = await this.pool.query<ProfileRow>(
    `SELECT id, name, headline, summary, location, email, links, verified, created_at, updated_at
     FROM candidate_profile
     WHERE id = $1`,                                                  
    [candidateId],
  );
    const profileRow=profileResult.rows[0];
    if(!profileRow){
      return null;
    }
    const [skillResult, experienceResult, projectResult, educationResult, preferenceResult] =
      await Promise.all([
        this.pool.query<SkillRow>(`SELECT id,candidate_id,skill_name,proficiency_level FROM candidate_skill WHERE candidate_id = $1`,[candidateId],),
        this.pool.query<ExperienceRow>(`SELECT id,candidate_id,company_name,job_title,start_date,end_date,is_current,bullets FROM work_experience where candidate_id=$1 ORDER BY start_date DESC NULLS LAST`, [candidateId]),
        this.pool.query<ProjectRow>(`SELECT id,candidate_id,name,tech,bullets FROM project WHERE candidate_id=$1 `, [candidateId]),
        this.pool.query<EducationRow>(`SELECT id,candidate_id,institution_name,degree,field_of_study,year from education where candidate_id=$1`, [candidateId]),
        this.pool.query<PreferenceRow>(`SELECT id,candidate_id,employment_types,preferred_roles,work_arrangements,preferred_locations,minimum_salary,salary_currency from job_preference where candidate_id=$1`, [candidateId]),
      ]);
    const data: ProfileData = {
      name: profileRow.name,
      headline: profileRow.headline ?? '',
      email: profileRow.email ?? '',
      location: profileRow.location ?? '',
      links: profileRow.links,
      summary: profileRow.summary ?? '',
      skills: skillResult.rows.map((row) => row.skill_name),
      experience: experienceResult.rows.map(toExperience),
      projects: projectResult.rows.map(toProject),
      education: educationResult.rows.map(toEducation),
      preferences: toPreferences(preferenceResult.rows[0]),
    };

    return {
      ...data,
      id: profileRow.id,
      initials: getInitials(data.name),
      verified: profileRow.verified,
      completeness: getCompleteness(data),
      createdAt: profileRow.created_at,
      updatedAt: profileRow.updated_at
    };
  }

  async create(input: CreateProfileInput): Promise<CandidateProfile> {
    // One INSERT is atomic on its own, so no transaction is needed.
    // verified defaults to false; the lists start empty.
    const inserted = await this.pool.query<{ id: string }>(
      'INSERT INTO candidate_profile (name, email) VALUES ($1, $2) RETURNING id',
      [input.name.trim(), input.email.trim()],
    );
    // The row was just created, so findById can't return null here (hence the `!`).
    return (await this.findById(inserted.rows[0].id))!;
  }

  async saveConfirmed(candidateId: string, data: ProfileData): Promise<CandidateProfile | null> {
    const client = await this.pool.connect();
    try {
      await client.query('BEGIN');

      // Overwrite the profile with the confirmed data.
      // $1 name, $2 headline, $3 email, $4 location, $5 links, $6 summary, $7 candidateId
      const updated = await client.query(
        `UPDATE candidate_profile
         SET name = $1, headline = $2, email = $3, location = $4, links = $5, summary = $6,
             verified = true, updated_at = now()
         WHERE id = $7`,
        [data.name, data.headline, data.email, data.location, data.links, data.summary, candidateId],
      );
      if (updated.rowCount === 0) {
        await client.query('ROLLBACK');
        return null;                                  // that id doesn't exist
      }

      // Replace every list: the same helpers as update()
      await replaceSkills(client, candidateId, data.skills);
      await replaceProjects(client, candidateId, data.projects);
      await replaceExperience(client, candidateId, data.experience);
      await replaceEducation(client, candidateId, data.education);
      await replacePreferences(client, candidateId, data.preferences);
      await client.query('COMMIT');
    } catch (err) {
      await client.query('ROLLBACK');
      throw err;
    } finally {
      client.release();
    }

    return this.findById(candidateId);
  }

  async update(candidateId: string, changes: UpdateProfileInput): Promise<CandidateProfile | null> {
    const client= await this.pool.connect();
    try{
      await client.query('BEGIN');
      const existing = await client.query(
        'SELECT id FROM candidate_profile WHERE id = $1 FOR UPDATE',
        [candidateId],
      );
      if (existing.rowCount === 0) {                 
        await client.query('ROLLBACK');                
        return null;
      }
      // Simple fields: API field name → database column.
      // Only these columns can ever appear in the SQL (safe from SQL injection).
      const columns = {
        name: 'name',
        headline: 'headline',
        email: 'email',
        location: 'location',
        links: 'links',
        summary: 'summary',
      } as const;

      const setParts: string[] = ['updated_at = now()'];   // always bump updated_at
      const values: unknown[] = [candidateId];             // $1 = candidateId

      for (const field of Object.keys(columns) as (keyof typeof columns)[]) {
        const value = changes[field];
        if (value !== undefined) {                         // only fields that were sent
          values.push(value);                              // becomes $2, $3, ...
          setParts.push(`${columns[field]} = $${values.length}`);
        }
      }

      await client.query(
        `UPDATE candidate_profile SET ${setParts.join(', ')} WHERE id = $1`,
        values,
      );

      if (changes.skills !== undefined) {
        await replaceSkills(client, candidateId, changes.skills);
      }
      if (changes.projects !== undefined) {
        await replaceProjects(client, candidateId, changes.projects);
      }
      if (changes.experience !== undefined) {
        await replaceExperience(client, candidateId, changes.experience);
      }
      if (changes.education !== undefined) {
        await replaceEducation(client, candidateId, changes.education);
      }
      if (changes.preferences !== undefined) {
        await replacePreferences(client, candidateId, changes.preferences);
      }

      await client.query('COMMIT');
    }catch(err){
      await client.query('ROLLBACK');
      throw err;
    }finally{
      client.release();
    }
    return this.findById(candidateId);
  }

  async deleteSkill(candidateId: string, skillName: string): Promise<boolean> {
    const result = await this.pool.query(
      'DELETE FROM candidate_skill WHERE candidate_id = $1 AND lower(skill_name) = lower($2)',
      [candidateId, skillName],
    );
    if (result.rowCount === 0) {
      return false;   // no such candidate, or the candidate doesn't have this skill
    }
    await this.pool.query('UPDATE candidate_profile SET updated_at = now() WHERE id = $1', [candidateId]);
    return true;
  }
}

function toExperience(row: ExperienceRow): Experience {
  return {
    id: row.id,
    role: row.job_title,                   
    organization: row.company_name,          
    start: row.start_date ?? '',      
    end: row.end_date ?? undefined,   
    bullets: row.bullets,
  };
}

function toProject(row: ProjectRow):Project{
  return { 
    id:row.id,
    name: row.name,
    tech: row.tech,
    bullets: row.bullets,
  }
}

function toEducation(row: EducationRow):Education{
  return {
    id: row.id,
    degree: row.degree,
    school: row.institution_name,
    year: row.year ?? ""
  }
}

function toPreferences(row: PreferenceRow | undefined): CandidatePreferences {
  if (!row) {
    return { locations: [], arrangements: [], employmentTypes: [] };   // no preference row
  }
  return {
    locations: row.preferred_locations ?? [],
    arrangements: (row.work_arrangements ?? []) as WorkArrangement[],
    employmentTypes: row.employment_types as EmploymentType[],
    minSalary: row.minimum_salary === null ? undefined : Number(row.minimum_salary),
  };
}

function getInitials(name: string): string{
  return name.split(" ").filter((word)=>word!=="").map((word)=>word[0]).join('').toUpperCase().slice(0,2);
}

function getCompleteness(profile: ProfileData): number{
  const checks = [
    profile.name !=='',
    profile.email !=='',
    profile.location !=='',
    profile.headline !=='',
    profile.summary !== '',
    profile.links.length>0,
    profile.skills.length>0,
    profile.experience.length>0,
    profile.education.length>0,
    profile.projects.length>0,
  ];
  const filled=checks.filter((ok)=>ok).length;
  return Math.round((filled/checks.length)*100);
}

/**
 * Upsert, matched by skill name (case-insensitive): a skill that is still in
 * the list keeps its row, so columns the frontend doesn't send
 * (proficiency_level) are kept.
 */
async function replaceSkills(client: PoolClient, candidateId: string, skills: string[]): Promise<void> {
  // 1. Remove the skills that are no longer in the list.
  await client.query(
    `DELETE FROM candidate_skill
     WHERE candidate_id = $1 AND NOT (lower(skill_name) = ANY($2::text[]))`,
    [candidateId, skills.map((name) => name.toLowerCase())],
  );
  // 2. Add new skills. An existing one only gets its spelling updated
  //    ('python' -> 'Python'); its other columns stay as they are.
  for (const skillName of skills) {
    await client.query(
      `INSERT INTO candidate_skill (candidate_id, skill_name) VALUES ($1, $2)
       ON CONFLICT (candidate_id, lower(skill_name)) DO UPDATE SET skill_name = EXCLUDED.skill_name`,
      [candidateId, skillName],
    );
  }
}

async function replaceProjects(client: PoolClient, candidateId: string, projects: Project[]): Promise<void> {
  await client.query('DELETE FROM project WHERE candidate_id = $1', [candidateId]);
  for (const project of projects) {
    await client.query(
      'INSERT INTO project (candidate_id, name, tech, bullets) VALUES ($1, $2, $3, $4)',
      [candidateId, project.name, project.tech, project.bullets],
    );
  }
}

async function replaceExperience(client: PoolClient, candidateId: string, experience: Experience[]): Promise<void> {
  await client.query('DELETE FROM work_experience WHERE candidate_id = $1', [candidateId]);
  for (const job of experience) {
    await client.query(
      `INSERT INTO work_experience (candidate_id, company_name, job_title, start_date, end_date, is_current, bullets)
       VALUES ($1, $2, $3, $4, $5, $6, $7)`,
      [
        candidateId,
        job.organization,                    // organization → company_name
        job.role,                    // role → job_title
        job.start || null,          // '' → NULL
        job.end || null,            // undefined → NULL
        job.end === undefined,            // current job = no end date
        job.bullets,
      ],
    );
  }
}

/**
 * Upsert, matched by id: an item the frontend got from GET comes back with its
 * id and updates that row, so columns the frontend doesn't send
 * (field_of_study, gpa) are kept. An item without a known id is new.
 */
async function replaceEducation(client: PoolClient, candidateId: string, education: Education[]): Promise<void> {
  // New items may carry a temporary frontend id (e.g. 'edu-1'), which isn't a
  // UUID and can't match a row, so only real UUIDs count as existing ids.
  const keptIds = education.map((e) => e.id).filter((id) => isUuid(id));

  // 1. Remove the rows that are no longer in the list.
  await client.query(
    `DELETE FROM education WHERE candidate_id = $1 AND NOT (id = ANY($2::uuid[]))`,
    [candidateId, keptIds],
  );

  for (const e of education) {
    // 2. Existing row: update only the columns the frontend knows about.
    //    `candidate_id = $2` stops anyone from editing another candidate's row.
    if (isUuid(e.id)) {
      const updated = await client.query(
        `UPDATE education SET institution_name = $3, degree = $4, year = $5
         WHERE id = $1 AND candidate_id = $2`,
        [e.id, candidateId, e.school, e.degree, e.year || null],
      );
      if (updated.rowCount === 1) {
        continue;   // done with this item, go to the next one
      }
    }
    // 3. New item (or an id that doesn't exist): insert it, the DB generates the id.
    await client.query(
      `INSERT INTO education (candidate_id, institution_name, degree, year) VALUES ($1, $2, $3, $4)`,
      [candidateId, e.school, e.degree, e.year || null],
    );
  }
}

async function replacePreferences(client: PoolClient, candidateId: string, preferences: CandidatePreferences): Promise<void> {
  // Upsert instead of delete + insert: the frontend doesn't send
  // preferred_roles or salary_currency, so they must be kept, not wiped.
  await client.query(
    `INSERT INTO job_preference (candidate_id, preferred_locations, work_arrangements, employment_types, minimum_salary)
     VALUES ($1, $2, $3, $4, $5)
     ON CONFLICT (candidate_id) DO UPDATE SET
       preferred_locations = EXCLUDED.preferred_locations,
       work_arrangements   = EXCLUDED.work_arrangements,
       employment_types    = EXCLUDED.employment_types,
       minimum_salary      = EXCLUDED.minimum_salary`,
    [
      candidateId,
      preferences.locations ?? [],
      preferences.arrangements ?? [],
      preferences.employmentTypes ?? [],
      preferences.minSalary ?? null,
    ],
  );
}
